services:
  # Documentation and examples can be found on https://giscience.github.io/openrouteservice/run-instance/running-with-docker
  ors-app:
    ports:
      - "8080:8082"
      - "9001:9001"
    image: openrouteservice/openrouteservice:v8.1.0
    user: "1000:1000"
    volumes:
      - ./docker/ors/graphs:/home/ors/graphs
      - ./docker/ors/elevation_cache:/home/ors/elevation_cache
      - ./docker/ors/logs:/home/ors/logs
      - ./docker/ors/config:/home/ors/config
      - ./docker/data:/home/ors/files
    environment:
      ors.engine.source_file: /home/ors/files/monaco-latest.osm.pbf

      REBUILD_GRAPHS: false # Set to True to rebuild graphs on container start.
      CONTAINER_LOG_LEVEL: INFO # Log level for the container. Possible values: DEBUG, INFO, WARNING, ERROR, CRITICAL
      # If you don't want the default ors-config.yml you can specify a custom file name, that should match the file in
      # your 'config' volume mount.
      #ORS_CONFIG_LOCATION: /home/ors/config/my-ors-config.yml  # Location of your ORS configuration file in the docker container

      # ------------------ JAVA OPTS ------------------ #
      # Configure the memory settings for JAVA or pass additional opts
      # Fore more available ENV properties see Prepare CATALINA_OPTS and JAVA_OPTS
      # in https://github.com/GIScience/openrouteservice/blob/main/docker-entrypoint.sh
      XMS: 1g # start RAM assigned to java
      XMX: 1g # max RAM assigned to java. Rule of Thumb: <PBF-size> * <profiles> * 2
      # Example: 1.5 GB pbf size, two profiles (car and foot-walking)
      # -> 1.5 * 2 * 2 = 6. Set xmx to be AT LEAST `-Xmx6g`
      ADDITIONAL_JAVA_OPTS: "" # further options you want to pass to the java command

  overpass-api:
    image: wiktorn/overpass-api
    ports:
      - "7777:80"
    environment:
      OVERPASS_PLANET_URL: http://download.geofabrik.de/europe/monaco-latest.osm.bz2
      OVERPASS_MODE: init
    volumes:
      - ./docker/overpass:/db
      - ./docker/data:/data
