packages:
  - "apps/*"
  - "packages/pentatrion-design"
  - "packages/maplibre-react-components"
  - "packages/maplibre-theme"
  - "packages/pentatrion-fonts"
  - "packages/pentatrion-geo"
  - "extra/swagger"
  - "extra/assets"
