
ors:
  engine:
    source_file: /home/ors/files/example-heidelberg.osm.pbf
    profiles:
      car:
        profile: driving-car
        enabled: true
      bike-regular:
        enabled: true
        profile: cycling-regular
        encoder_options:
          consider_elevation: true
          turn_costs: true
          block_fords: false
      hiking:
        enabled: true
        profile: foot-hiking
        encoder_options:
          block_fords: false

