interface LayerInfos {
  id: string;
  label: string;
  description?: string;
  thumbnail: string;
  thumbnailPosition: [number, number];
  style: string;
}

export type LayerId = keyof typeof layersById;

export const layers: LayerId[] = [
  "ign-satellite",
  "maptiler",
  "ign-admin_express-adminexpress",
  "ign-bd_topo-classique",
  "ign-bd_topo-bati",
  "ign-bd_topo-hydrographie",
  "ign-bd_topo-routier",
  "ign-bd_topo-bati_date",
  "ign-bd_topo-bati_etages",
  "ign-isohypse-isohypse_multicolore",
  "ign-isohypse-isohypse_monochrome_marron",
  "ign-isohypse-isohypse_monochrome_orange",
  "ign-ocsge-ocsge_couverture",
  "ign-ocsge-ocsge_usage",
  "ign-ocsge-ocsge_occupation",
  "ign-pci-noir_et_blanc",
  "ign-pci-pci",
  "ign-plan_ign-standard",
  "ign-plan_ign-attenue",
  "ign-plan_ign-gris",
  "ign-plan_ign-sans_toponymes",
  "ign-plan_ign-toponymes",
  "ign-plan_ign-accentue",
  "ign-plan_ign-classique",
  "ign-plan_ign-epure",
];

export const layersById = {
  "ign-satellite": {
    id: "ign-satellite",
    label: "IGN Satellite",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/satellite.json",
  } satisfies LayerInfos,
  maptiler: {
    id: "maptiler",
    label: "Map tiler",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "https://api.maptiler.com/maps/streets/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL",
  } satisfies LayerInfos,
  /* tuiles vectorielles */
  "ign-admin_express-adminexpress": {
    id: "ign-admin_express-adminexpress",
    label: "Admin Express",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/ADMIN_EXPRESS/adminexpress.json",
  },
  "ign-bd_topo-classique": {
    id: "ign-bd_topo-classique",
    label: "Topo Classique",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/BDTOPO/classique.json",
  },
  "ign-bd_topo-bati": {
    id: "ign-bd_topo-bati",
    label: "Topo Bati",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/BDTOPO/bati.json",
  },
  "ign-bd_topo-hydrographie": {
    id: "ign-bd_topo-hydrographie",
    label: "Topo Hydrographie",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/BDTOPO/hydrographie.json",
  },
  "ign-bd_topo-routier": {
    id: "ign-bd_topo-routier",
    label: "Topo Routier",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/BDTOPO/routier.json",
  },
  "ign-bd_topo-bati_date": {
    id: "ign-bd_topo-bati_date",
    label: "Topo Bati date",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/BDTOPO/bati_date.json",
  },
  "ign-bd_topo-bati_etages": {
    id: "ign-bd_topo-bati_etages",
    label: "Topo Bati étages",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/BDTOPO/bati_etages.json",
  },
  "ign-isohypse-isohypse_multicolore": {
    id: "ign-isohypse-isohypse_multicolore",
    label: "Isohypse multi",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/ISOHYPSE/isohypse_multicolore.json",
  },
  "ign-isohypse-isohypse_monochrome_marron": {
    id: "ign-isohypse-isohypse_monochrome_marron",
    label: "Isohypse marron",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/ISOHYPSE/isohypse_monochrome_marron.json",
  },
  "ign-isohypse-isohypse_monochrome_orange": {
    id: "ign-isohypse-isohypse_monochrome_orange",
    label: "Isohypse orange",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/ISOHYPSE/isohypse_monochrome_orange.json",
  },
  "ign-ocsge-ocsge_couverture": {
    id: "ign-ocsge-ocsge_couverture",
    label: "OCS couverture",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/OCSGE/ocsge_couverture.json",
  },
  "ign-ocsge-ocsge_usage": {
    id: "ign-ocsge-ocsge_usage",
    label: "OCS Usage",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/OCSGE/ocsge_usage.json",
  },
  "ign-ocsge-ocsge_occupation": {
    id: "ign-ocsge-ocsge_occupation",
    label: "OCS Occupation",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/OCSGE/ocsge_occupation.json",
  },
  "ign-pci-noir_et_blanc": {
    id: "ign-pci-noir_et_blanc",
    label: "Parcellaire n&b",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PCI/noir_et_blanc.json",
  },
  "ign-pci-pci": {
    id: "ign-pci-pci",
    label: "Parcellaire",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PCI/pci.json",
  },
  "ign-plan_ign-standard": {
    id: "ign-plan_ign-standard",
    label: "Plan standard",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/standard.json",
  },
  "ign-plan_ign-attenue": {
    id: "ign-plan_ign-attenue",
    label: "Plan attenué",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/attenue.json",
  },
  "ign-plan_ign-gris": {
    id: "ign-plan_ign-gris",
    label: "Plan gris",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/gris.json",
  },
  "ign-plan_ign-sans_toponymes": {
    id: "ign-plan_ign-sans_toponymes",
    label: "Plan sans toponymes",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/sans_toponymes.json",
  },
  "ign-plan_ign-toponymes": {
    id: "ign-plan_ign-toponymes",
    label: "Toponymes",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/toponymes.json",
  },
  "ign-plan_ign-accentue": {
    id: "ign-plan_ign-accentue",
    label: "Plan accentué",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/accentue.json",
  },
  "ign-plan_ign-classique": {
    id: "ign-plan_ign-classique",
    label: "Plan classique",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/classique.json",
  },
  "ign-plan_ign-epure": {
    id: "ign-plan_ign-epure",
    label: "Plan épuré",
    description: "",
    thumbnail: "/thumbnail/layer-preview-1x.jpg",
    thumbnailPosition: [0, 0],
    style: "/styles/ign/PLAN.IGN/epure.json",
  },
};
